// Generated by github.com/hypermusk/hypermusk
// DO NOT EDIT

#import <Foundation/Foundation.h>


@interface Api : NSObject
@property (nonatomic, strong) NSString * baseURL;
@property (nonatomic, assign) BOOL verbose;
@property (nonatomic, assign) NSTimeInterval requestTimeoutInterval;
+ (Api *) get;

@end



// --- Product ---
@interface Product : NSObject<NSCoding>

@property (nonatomic, strong) NSString * id;
@property (nonatomic, strong) NSString * name;
@property (nonatomic, strong) NSString * photoLink;
@property (nonatomic, strong) NSNumber * price;
@property (nonatomic, strong) NSString * validFrom;
@property (nonatomic, strong) NSString * validTo;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- User ---
@interface User : NSObject<NSCoding>

@property (nonatomic, strong) NSString * name;
@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) NSString * avatarLink;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- ProductInput ---
@interface ProductInput : NSObject<NSCoding>

@property (nonatomic, strong) NSString * name;
@property (nonatomic, strong) NSNumber * price;
@property (nonatomic, strong) NSString * photoLink;
@property (nonatomic, strong) NSString * validFrom;
@property (nonatomic, strong) NSString * validTo;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- UserInput ---
@interface UserInput : NSObject<NSCoding>

@property (nonatomic, strong) NSString * name;
@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) NSString * avatarLink;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- Order ---
@interface Order : NSObject<NSCoding>

@property (nonatomic, strong) NSString * date;
@property (nonatomic, strong) Product * product;
@property (nonatomic, strong) NSArray * users;
@property (nonatomic, strong) NSNumber * count;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end


// === Interfaces ===

// --- PutProductParams ---
@interface ServicePutProductParams : NSObject

@property (nonatomic, strong) NSString * id;
@property (nonatomic, strong) ProductInput * input;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PutProductResults ---
@interface ServicePutProductResults : NSObject

@property (nonatomic, strong) Product * product;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveProductParams ---
@interface ServiceRemoveProductParams : NSObject

@property (nonatomic, strong) NSString * id;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveProductResults ---
@interface ServiceRemoveProductResults : NSObject

@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PutUserParams ---
@interface ServicePutUserParams : NSObject

@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) UserInput * input;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PutUserResults ---
@interface ServicePutUserResults : NSObject

@property (nonatomic, strong) User * user;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveUserParams ---
@interface ServiceRemoveUserParams : NSObject

@property (nonatomic, strong) NSString * email;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveUserResults ---
@interface ServiceRemoveUserResults : NSObject

@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PutOrderParams ---
@interface ServicePutOrderParams : NSObject

@property (nonatomic, strong) NSString * date;
@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) NSString * productId;
@property (nonatomic, strong) NSNumber * count;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PutOrderResults ---
@interface ServicePutOrderResults : NSObject

@property (nonatomic, strong) Order * order;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveOrderParams ---
@interface ServiceRemoveOrderParams : NSObject

@property (nonatomic, strong) NSString * date;
@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) NSString * productId;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- RemoveOrderResults ---
@interface ServiceRemoveOrderResults : NSObject

@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- ProductListOfDateParams ---
@interface ServiceProductListOfDateParams : NSObject

@property (nonatomic, strong) NSString * date;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- ProductListOfDateResults ---
@interface ServiceProductListOfDateResults : NSObject

@property (nonatomic, strong) NSArray * products;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- OrderListOfDateParams ---
@interface ServiceOrderListOfDateParams : NSObject

@property (nonatomic, strong) NSString * date;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- OrderListOfDateResults ---
@interface ServiceOrderListOfDateResults : NSObject

@property (nonatomic, strong) NSArray * orders;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyAvaliableProductsParams ---
@interface ServiceMyAvaliableProductsParams : NSObject

@property (nonatomic, strong) NSString * date;
@property (nonatomic, strong) NSString * email;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyAvaliableProductsResults ---
@interface ServiceMyAvaliableProductsResults : NSObject

@property (nonatomic, strong) NSArray * products;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyOrdersParams ---
@interface ServiceMyOrdersParams : NSObject

@property (nonatomic, strong) NSString * date;
@property (nonatomic, strong) NSString * email;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyOrdersResults ---
@interface ServiceMyOrdersResults : NSObject

@property (nonatomic, strong) NSArray * orders;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- Top3PopularProductsParams ---
@interface ServiceTop3PopularProductsParams : NSObject

@property (nonatomic, strong) NSString * date;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- Top3PopularProductsResults ---
@interface ServiceTop3PopularProductsResults : NSObject

@property (nonatomic, strong) NSArray * products;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyTop3FavouriteProductsParams ---
@interface ServiceMyTop3FavouriteProductsParams : NSObject

@property (nonatomic, strong) NSString * email;
@property (nonatomic, strong) NSString * date;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- MyTop3FavouriteProductsResults ---
@interface ServiceMyTop3FavouriteProductsResults : NSObject

@property (nonatomic, strong) NSArray * products;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end


@interface Service : NSObject- (NSDictionary*) dictionary;

- (ServicePutProductResults *) putProduct:(NSString *)id input:(ProductInput *)input;
- (void) putProduct:(NSString *)id input:(ProductInput *)input success:(void (^)(ServicePutProductResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (NSError *) removeProduct:(NSString *)id;
- (void) removeProduct:(NSString *)id success:(void (^)(NSError *error))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServicePutUserResults *) putUser:(NSString *)email input:(UserInput *)input;
- (void) putUser:(NSString *)email input:(UserInput *)input success:(void (^)(ServicePutUserResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (NSError *) removeUser:(NSString *)email;
- (void) removeUser:(NSString *)email success:(void (^)(NSError *error))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServicePutOrderResults *) putOrder:(NSString *)date email:(NSString *)email productId:(NSString *)productId count:(NSNumber *)count;
- (void) putOrder:(NSString *)date email:(NSString *)email productId:(NSString *)productId count:(NSNumber *)count success:(void (^)(ServicePutOrderResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (NSError *) removeOrder:(NSString *)date email:(NSString *)email productId:(NSString *)productId;
- (void) removeOrder:(NSString *)date email:(NSString *)email productId:(NSString *)productId success:(void (^)(NSError *error))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceProductListOfDateResults *) productListOfDate:(NSString *)date;
- (void) productListOfDate:(NSString *)date success:(void (^)(ServiceProductListOfDateResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceOrderListOfDateResults *) orderListOfDate:(NSString *)date;
- (void) orderListOfDate:(NSString *)date success:(void (^)(ServiceOrderListOfDateResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceMyAvaliableProductsResults *) myAvaliableProducts:(NSString *)date email:(NSString *)email;
- (void) myAvaliableProducts:(NSString *)date email:(NSString *)email success:(void (^)(ServiceMyAvaliableProductsResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceMyOrdersResults *) myOrders:(NSString *)date email:(NSString *)email;
- (void) myOrders:(NSString *)date email:(NSString *)email success:(void (^)(ServiceMyOrdersResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceTop3PopularProductsResults *) top3PopularProducts:(NSString *)date;
- (void) top3PopularProducts:(NSString *)date success:(void (^)(ServiceTop3PopularProductsResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceMyTop3FavouriteProductsResults *) myTop3FavouriteProducts:(NSString *)email date:(NSString *)date;
- (void) myTop3FavouriteProducts:(NSString *)email date:(NSString *)date success:(void (^)(ServiceMyTop3FavouriteProductsResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;
@end

